osef_user:
    resource: "@OSEFUserBundle/Resources/config/routing.yml"
    prefix:   /

osef_common:
    resource: "@OSEFCommonBundle/Resources/config/routing.yml"
    prefix:   /

osef_app:
    resource: "@OSEFAppBundle/Resources/config/routing.yml"
    prefix:   /

